In [1]:
import pandas as pd

# Load a dataset directly from the internet
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

df.head()
df.describe()
df.info()

# Count classes
df['species'].value_counts()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [2]:
import numpy as np

a = np.array([3,4,5])
b = np.array([7,8,9])

print(a + b)
print(a * 3)
print(b + 5)
print(np.dot(a,b))

M = np.array([3,4],[6,7])
N = np.array([5,9],[4,3])
print(np.matmul(M,N))

[10 12 14]
[ 9 12 15]
[12 13 14]
98


TypeError: Field elements must be 2- or 3-tuples, got '6'